version: '3.0'
services:
  eol-repo-elasticsearch:
    image: elasticsearch
    container_name: eol-repo-elasticsearch
    restart: always
    environment:
      - TZ=America/New_York
      - ES_JAVA_OPTS=-Xms512m -Xmx30g
    volumes:
      - /data/eol-repo-es/data:/usr/share/elasticsearch/data
    networks:
      - docker_eolnet
  eol-repo-memcached:
    image: memcached
    container_name: eol-repo-memcached
    restart: always
    environment:
      - TZ=America/New_York
    command: memcached -m 4096m
    networks:
      - docker_eolnet
  eol-repo-mysql:
    image: mysql
    container_name: eol-repo-mysql
    restart: always
    env_file:
      - resources/staging.env
    volumes:
      - /data/eol-repo-mysql:/var/lib/mysql
    networks:
      - docker_eolnet
  eol-repo-app:
    image: encoflife/eol-repo-app
    container_name: eol-repo-app
    restart: always
    volumes:
      - /data/eol-repo-app:/u/apps/harvester/public/data
      - ./bin/init.sh:/etc/my_init.d/init.sh
      - ./resources/secrets.yml:/u/apps/secrets.yml
    depends_on:
      - eol-repo-elasticsearch
      - eol-repo-mysql
      - eol-repo-memcached
    links:
      - eol-repo-elasticsearch:elasticsearch
      - eol-repo-memcached:memcached
      - eol-repo-mysql:mysql
    env_file:
      - resources/staging.env
    ports:
      - 3001:3000
    networks:
      - docker_eolnet
networks:
  docker_eolnet:
    external: true
