version: '3.0' # Note that the verison is NOT for this document, but for the version of docker-compose itself. Keep.
services:
  eol-repo-elasticsearch:
    image: elasticsearch
    container_name: eol-repo-elasticsearch
    restart: always
    environment:
      - TZ=America/New_York
      - ES_JAVA_OPTS=-Xms512m -Xmx30g
    volumes:
      - /data/eol-repo-es/data:/usr/share/elasticsearch/data
    networks:
      - docker_eolnet
  eol-repo-memcached:
    image: memcached
    container_name: eol-repo-memcached
    restart: always
    environment:
      - TZ=America/New_York
    command: memcached -m 4096m
    networks:
      - docker_eolnet
  eol-repo-mysql:
    image: mysql:5.7.12
    container_name: eol-repo-mysql
    restart: always
    env_file:
      - resources/staging.env
    volumes:
      - /data/eol-repo-mysql:/var/lib/mysql
    networks:
      - docker_eolnet
  eol-repo-app:
    build: ..
    image: harvester_v3
    container_name: eol-repo-app
    restart: always
    volumes:
      - /data/eol-repo-app:/app/public/data
      - /data/eol-repo-app/tmp:/tmp
      - /tmp:/app/tmp
    depends_on:
      - eol-repo-elasticsearch
      - eol-repo-mysql
      - eol-repo-memcached
    links:
      - eol-repo-elasticsearch:elasticsearch
      - eol-repo-memcached:memcached
      - eol-repo-mysql:mysql
    env_file:
      - resources/staging.env
    ports:
      - 3001:3000
    networks:
      - docker_eolnet
networks:
  docker_eolnet:
    external: true
